with open("docs/method_notes.md", "a", encoding="utf-8") as f:
    f.write("\n## Pass 1 Relevance Gate Decision Procedure (30 September 2026)\n")
    f.write("*(Note: This procedure was derived by adjudicating 18 disagreement cases between batched and unbatched configurations to eliminate prompt ambiguity.)*\n\n")
    f.write("### Decision procedure\n\n")
    f.write("Apply these steps in order.\n\n")
    f.write("STEP 1 — Is the person trying to reach a photo or video they believe exists in\n")
    f.write("their own Google Photos library?\n")
    f.write("  If no, the decision is \"no\". This includes questions about the search feature\n")
    f.write("  itself (its placement, how to disable it), general feature discussion,\n")
    f.write("  problems on other platforms or other apps, and app issues where no attempt to\n")
    f.write("  reach a photo is described.\n")
    f.write("  If yes, continue to step 2.\n\n")
    f.write("STEP 2 — Do they name a specific target: a particular photo, event, person,\n")
    f.write("place, object or document, or a concrete query they ran?\n")
    f.write("  If yes, the decision is \"yes\".\n")
    f.write("  If no, but they describe attempting retrieval, the decision is \"partial\".\n\n")
    f.write("STEP 3 — OVERRIDE. If the person states the photo or video was deleted, by them\n")
    f.write("or anyone else, or asks about recovery or restoration, the decision is \"no\",\n")
    f.write("regardless of steps 1 and 2.\n\n")
    f.write("Notes:\n")
    f.write("- The CAUSE of the failure is not the criterion. Someone who cannot reach photos\n")
    f.write("  they believe exist has a retrieval problem whether the cause is search, sync,\n")
    f.write("  indexing or a display bug.\n")
    f.write("- A person who describes a query they ran and what they expected back has named\n")
    f.write("  a specific target, even if they give it as an example of a broader problem.\n")
    f.write("- Inventory requests (\"find all duplicates\", \"photos not in any album\") pass\n")
    f.write("  step 1 but fail step 2, so they are \"partial\".\n")
    f.write("- Where the person does not know whether a photo is deleted or merely hidden,\n")
    f.write("  step 3 does not apply — their searching behaviour is still evidence.\n")
